apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecommerce-api
  labels:
    app: api
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecommerce-frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecommerce-admin
  labels:
    app: admin
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: admin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecommerce-auth
  labels:
    app: auth
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: auth
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecommerce-payment
  labels:
    app: payment
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: payment
