apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: "local-dev"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_PASSWORD: "super-secure-local-password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hashicorp/http-echo:latest
        args:
        - "-text=Backend Echo Service. Env: $(ENV_NAME), Redis Host: $(REDIS_HOST), DB Password: $(DB_PASS)"
        ports:
        - containerPort: 5678
        env:
        - name: ENV_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: APP_ENV
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_HOST
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 8080
    targetPort: 5678
  selector:
    app: backend
