apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-backend-config
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.environment.envName | quote }}
  REDIS_HOST: "{{ include "myapp.fullname" . }}-redis"
