apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-backend-secret
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.dbPassword | quote }}
