# E-Commerce Platform values

environment:
  envName: "production-like"
  # DNS route inside Minikube to access LocalStack running on host machine
  awsEndpoint: "http://host.minikube.internal:4566"
  awsRegion: "us-east-1"

api:
  replicas: 1
  image:
    repository: "node"
    tag: "18-alpine"
    pullPolicy: "IfNotPresent"

worker:
  replicas: 1
  image:
    repository: "node"
    tag: "18-alpine"
    pullPolicy: "IfNotPresent"

frontend:
  replicas: 1
  image:
    repository: "nginx"
    tag: "alpine"
    pullPolicy: "IfNotPresent"

admin:
  replicas: 1
  image:
    repository: "nginx"
    tag: "alpine"
    pullPolicy: "IfNotPresent"

auth:
  replicas: 1
  image:
    repository: "node"
    tag: "18-alpine"
    pullPolicy: "IfNotPresent"

payment:
  replicas: 1
  image:
    repository: "node"
    tag: "18-alpine"
    pullPolicy: "IfNotPresent"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: localhost
      paths:
        - path: /api/auth(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: auth
          backendPort: 3000
        - path: /api/payments(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: payment
          backendPort: 3000
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: api
          backendPort: 3000
        - path: /admin(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: admin
          backendPort: 80
        - path: /()(.*)
          pathType: ImplementationSpecific
          backendService: frontend
          backendPort: 80
    - host: ""
      paths:
        - path: /api/auth(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: auth
          backendPort: 3000
        - path: /api/payments(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: payment
          backendPort: 3000
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: api
          backendPort: 3000
        - path: /admin(/|$)(.*)
          pathType: ImplementationSpecific
          backendService: admin
          backendPort: 80
        - path: /()(.*)
          pathType: ImplementationSpecific
          backendService: frontend
          backendPort: 80

